services:
  autoscaling:
    build: .
    container_name: k8s-example-autoscaling-app
    ports:
      - "8080:8080"
    environment:
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=prometheus
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true

  prometheus:
    image: prom/prometheus:latest
    container_name: k8s-example-autoscaling-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: k8s-example-autoscaling-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change password for security
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards

  postgres:
    image: postgres:latest
    container_name: k8s-example-autoscaling-app
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  grafana_data: