apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath
#  selector:
#    matchLabels:
#      release: "stable"