apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
#  clusterIP: None  # Makes it headless for StatefulSets
  type: ClusterIP    # You can use NodePort or LoadBalancer depending on your setup