apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://k8s-example-autoscaling-prometheus:9090
    isDefault: true
    uid: prometheus_uid  # This UID helps link dashboards to the correct data source